version: "3.7"

services:
 scheduler:
  image: itsokaycz/scheduler-docker
  ports:
   - 3000:3000
  working_dir: /app
  environment:
   DB_HOST: mongodb
   authPath: ${SCHEDULER_AUTH_PATH}
   authCooke: ${SCHEDULER_AUTH_COOKIE}
 
 mongodb:
  image: mongo:4.4.10
  volumes:
   - scheduler-mongodb-data:/var/lib/mongodb

volumes:
 scheduler-mongodb-data:
